### PR TITLE
fix(upgrade): missing packages use min required and peerDep shoud use latest version

### PR DESCRIPTION
**Pull request by winchesHe**
## 📝 Description

Before

image

After

Cursor 2024-12-08 13 43 36

## ✅ Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (improve a current implementation without adding a new feature or fixing a bug)
- [ ] Improvement (non-breaking change which improves an existing feature)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### CODE REVIEW

**Comment by jrgarciadev** [comment]
I see the "theme" package is in the same 2.3.0? please check

**Comment by winchesHe** [comment]
> I see the "theme" package is in the same 2.3.0? please check

Fixed, current peerDependencies will also upgrade to latest version not required version

**Comment by winchesHe** [comment]
https://linear.app/nextui-inc/issue/ENG-1669/fetch-the-latest-version-of-the-peerdep

**Comment by winchesHe** [comment]
https://linear.app/nextui-inc/issue/ENG-1669/fetch-the-latest-version-of-the-peerdep

**Review by jrgarciadev — APPROVED** [review]

**Pull request merged**
