### PR TITLE
feat(updated): getPackageManagerInfo

### PR DESCRIPTION
**Pull request by ankiiisharma**
Updated getPackageManagerInfo to dynamically infer install and remove types based on package manager, ensuring type safety and flexibility.

## 📝 Description

- closes: #51

## ✅ Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Refactoring (improve a current implementation without adding a new feature or fixing a bug)
- [ ] Improvement (non-breaking change which improves an existing feature)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### CODE REVIEW

**Comment by winchesHe** [comment]
Sure, i will take a look

**Comment by winchesHe** [comment]
@ankiiisharma I have made some change, could you fix this ci error

After

image

image

**Comment by ankiiisharma** [comment]
@winchesHe , hey I checked this on my side . everything seems ok. can you please explain this error and why it is occurring?

**Comment by winchesHe** [comment]
image

You can run `git pull` and `npx tsc --noEmit` to check it

**Comment by ankiiisharma** [comment]
@winchesHe Done!, check please!

**Review by winchesHe — APPROVED** [review]

**Comment by winchesHe** [comment]
@ankiiisharma thx~

**Comment by ankiiisharma** [comment]
@winchesHe You're Welcome😊

**Pull request merged**
